export interface Product {
  id: string;
  brand: string;
  category: string;
  nameAr: string;
  nameEn: string;
  caseCount: number;
  pricePerPiece: number;  // RSP Per Piece WOVAT (credit, ex-VAT)
  pricePerCarton: number; // Carton RSP WOVAT (credit, ex-VAT)
  hasTax: boolean;
  image: string;
}

export const products: Product[] = [
  // ─── WADIFOOD — Olive Oil ───────────────────────────────────────────────────
  { id: "1",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر ممتاز 1/4 لتر دوريكا",                    nameEn: "Extra Virgin Olive Oil 1/4L – Dorica",              caseCount: 12, pricePerPiece: 284.21,  pricePerCarton: 3410.56,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "2",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر ممتاز 1/2 لتر دوريكا",                    nameEn: "Extra Virgin Olive Oil 1/2L – Dorica",              caseCount: 12, pricePerPiece: 503.82,  pricePerCarton: 6045.84,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "3",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر 1/4 لتر بلاستيك",                         nameEn: "Pure Olive Oil 1/4L – Plastic",                     caseCount: 12, pricePerPiece: 231.03,  pricePerCarton: 2772.40,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "4",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر ممتاز 1/4 لتر بلاستيك",                   nameEn: "Extra Pure Olive Oil 1/4L – Plastic",               caseCount: 12, pricePerPiece: 248.66,  pricePerCarton: 2983.96,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "5",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر 1/2 لتر بلاستيك",                         nameEn: "Pure Olive Oil 1/2L – Plastic",                     caseCount: 12, pricePerPiece: 406.57,  pricePerCarton: 4878.88,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "6",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر ممتاز 1/2 لتر بلاستيك",                   nameEn: "Extra Pure Olive Oil 1/2L – Plastic",               caseCount: 12, pricePerPiece: 438.89,  pricePerCarton: 5266.65,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "7",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر 1 لتر بلاستيك",                           nameEn: "Pure Olive Oil 1L – Plastic",                       caseCount: 12, pricePerPiece: 750.17,  pricePerCarton: 9002.02,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "8",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر ممتاز 1 لتر بلاستيك",                     nameEn: "Extra Pure Olive Oil 1L – Plastic",                 caseCount: 12, pricePerPiece: 808.79,  pricePerCarton: 9705.44,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "9",  brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر 2 لتر بلاستيك",                           nameEn: "Pure Olive Oil 2L – Plastic",                       caseCount:  6, pricePerPiece: 1384.06, pricePerCarton: 8304.34,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "10", brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر ممتاز 2 لتر بلاستيك",                     nameEn: "Extra Pure Olive Oil 2L – Plastic",                 caseCount:  6, pricePerPiece: 1483.75, pricePerCarton: 8902.52,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "11", brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون دومين نطرون بكر ممتاز 1/2 لتر امفورا",        nameEn: "Wadi El-Natron Extra Virgin Olive Oil 1/2L – Amphora", caseCount: 6, pricePerPiece: 948.54, pricePerCarton: 5691.24, hasTax: false, image: "/placeholder-product.svg" },
  { id: "12", brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر عادي 5 لتر",                               nameEn: "Pure Olive Oil 5L (Regular)",                       caseCount:  2, pricePerPiece: 2275.47, pricePerCarton: 4550.94,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "13", brand: "Wadifood", category: "Olive Oil",    nameAr: "زيت زيتون بكر ممتاز 5 لتر",                              nameEn: "Extra Pure Olive Oil 5L",                           caseCount:  2, pricePerPiece: 2522.73, pricePerCarton: 5045.45,  hasTax: false, image: "/placeholder-product.svg" },

  // ─── WADIFOOD — Vinegar ─────────────────────────────────────────────────────
  { id: "14", brand: "Wadifood", category: "Vinegar",      nameAr: "خل بلسمي ربع لتر دوريكا",                                nameEn: "Balsamic Vinegar 1/4L – Dorica",                    caseCount: 12, pricePerPiece: 69.30,   pricePerCarton: 831.59,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "15", brand: "Wadifood", category: "Vinegar",      nameAr: "خل تفاح ربع لتر دوريكا",                                 nameEn: "Apple Vinegar 1/4L – Dorica",                       caseCount: 12, pricePerPiece: 48.07,   pricePerCarton: 576.83,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "16", brand: "Wadifood", category: "Vinegar",      nameAr: "خل تفاح نص لتر بلاستيك",                                 nameEn: "Apple Vinegar 1/2L – Plastic",                      caseCount: 12, pricePerPiece: 60.78,   pricePerCarton: 729.38,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "17", brand: "Wadifood", category: "Vinegar",      nameAr: "خل طبيعى 1 لتر بلاستيك",                                 nameEn: "Natural Vinegar 1L – Plastic",                      caseCount: 12, pricePerPiece: 15.10,   pricePerCarton: 181.24,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "18", brand: "Wadifood", category: "Vinegar",      nameAr: "خل طبيعي 1/2 لتر بلاستك",                                nameEn: "Natural Vinegar 1/2L – Plastic",                    caseCount: 12, pricePerPiece: 8.52,    pricePerCarton: 102.21,   hasTax: true,  image: "/placeholder-product.svg" },

  // ─── WADIFOOD — Tomato Paste ────────────────────────────────────────────────
  { id: "19", brand: "Wadifood", category: "Tomato Paste", nameAr: "صلصة 320 جم برطمان",                                     nameEn: "Tomato Sauce 320g – Jar",                           caseCount: 12, pricePerPiece: 27.63,   pricePerCarton: 331.59,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "20", brand: "Wadifood", category: "Tomato Paste", nameAr: "صلصة طماطم 360 جم برطمان",                               nameEn: "Tomato Sauce 360g – Jar",                           caseCount: 12, pricePerPiece: 24.56,   pricePerCarton: 294.76,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "21", brand: "Wadifood", category: "Tomato Paste", nameAr: "صلصة طماطم 3 كيلو",                                      nameEn: "Tomato Paste 3kg",                                  caseCount:  4, pricePerPiece: 161.62,  pricePerCarton: 646.48,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "22", brand: "Wadifood", category: "Tomato Paste", nameAr: "صلصة طماطم 250 جم برطمان",                               nameEn: "Tomato Sauce 250g – Jar",                           caseCount: 12, pricePerPiece: 16.55,   pricePerCarton: 198.61,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "23", brand: "Wadifood", category: "Tomato Paste", nameAr: "صلصة طماطم 35 جم ساشيه",                                 nameEn: "Tomato Sauce 35g – Sachet",                         caseCount: 96, pricePerPiece: 2.21,    pricePerCarton: 211.86,   hasTax: true,  image: "/placeholder-product.svg" },

  // ─── WADIFOOD — Ketchup ─────────────────────────────────────────────────────
  { id: "24", brand: "Wadifood", category: "Ketchup",      nameAr: "كاتشب صحي – سادة – 300 جرام زجاجة",                     nameEn: "Healthy Ketchup – Plain – 300g Bottle",             caseCount: 12, pricePerPiece: 21.67,   pricePerCarton: 260.00,   hasTax: true,  image: "/placeholder-product.svg" },

  // ─── WADIFOOD — Speciality ──────────────────────────────────────────────────
  { id: "25", brand: "Wadifood", category: "Speciality",   nameAr: "طماطم مجففه 325 جم",                                     nameEn: "Sundried Tomatoes 325g",                            caseCount: 12, pricePerPiece: 119.22,  pricePerCarton: 1430.62,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "26", brand: "Wadifood", category: "Speciality",   nameAr: "زيتون اسود مفروم سادة 300 جرام برطمان",                  nameEn: "Plain Chopped Black Olives 300g – Jar",             caseCount: 12, pricePerPiece: 26.54,   pricePerCarton: 318.48,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "27", brand: "Wadifood", category: "Speciality",   nameAr: "زيتون اسود مفروم بالزعتر 300 جم برطمان",                 nameEn: "Chopped Black Olives with Thyme 300g – Jar",        caseCount: 12, pricePerPiece: 26.54,   pricePerCarton: 318.48,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "28", brand: "Wadifood", category: "Speciality",   nameAr: "اسود مفروم بالشطه 300 جرام برطمان",                      nameEn: "Chopped Black Olives with Chili 300g – Jar",        caseCount: 12, pricePerPiece: 26.54,   pricePerCarton: 318.48,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "29", brand: "Wadifood", category: "Speciality",   nameAr: "هريسه مفرومه 190 جم برطمان",                             nameEn: "Chopped Harissa 190g – Jar",                        caseCount: 12, pricePerPiece: 17.98,   pricePerCarton: 215.72,   hasTax: true,  image: "/placeholder-product.svg" },

  // ─── WADIFOOD — Beans ───────────────────────────────────────────────────────
  { id: "30", brand: "Wadifood", category: "Beans",        nameAr: "فول مدمس سادة 400 جرام صفيحة",                           nameEn: "Fava Beans Plain 400g – Tin",                       caseCount: 24, pricePerPiece: 18.29,   pricePerCarton: 438.90,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "31", brand: "Wadifood", category: "Beans",        nameAr: "فول مدمس سادة 700 جرام برطمان",                          nameEn: "Fava Beans Plain 700g – Jar",                       caseCount:  6, pricePerPiece: 32.14,   pricePerCarton: 192.83,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "32", brand: "Wadifood", category: "Beans",        nameAr: "فول مدمس سادة 3 كيلو صفيحة",                             nameEn: "Fava Beans Plain 3kg – Tin",                        caseCount:  4, pricePerPiece: 91.69,   pricePerCarton: 366.76,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "33", brand: "Wadifood", category: "Beans",        nameAr: "حبوب ذرة حلوه كاملة 400 جم صفيحة",                       nameEn: "Sweet Whole Corn 400g – Tin",                       caseCount: 24, pricePerPiece: 44.33,   pricePerCarton: 1064.00,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "34", brand: "Wadifood", category: "Beans",        nameAr: "فاصوليا حمراء 400 جم صفيحة",                             nameEn: "Red Kidney Beans 400g – Tin",                       caseCount: 24, pricePerPiece: 31.97,   pricePerCarton: 767.17,   hasTax: false, image: "/placeholder-product.svg" },

  // ─── WADIFOOD — Olives ──────────────────────────────────────────────────────
  { id: "35", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اخضر 650 جم برطمان",                               nameEn: "Green Olives 650g – Jar",                           caseCount:  6, pricePerPiece: 92.37,   pricePerCarton: 554.21,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "36", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اخضر 1 كجم",                                       nameEn: "Green Olives 1kg",                                  caseCount:  6, pricePerPiece: 112.77,  pricePerCarton: 676.62,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "37", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اخضر مخلى 650 جرام برطمان",                        nameEn: "Marinated Green Olives 650g – Jar",                 caseCount:  6, pricePerPiece: 116.66,  pricePerCarton: 699.93,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "38", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اخضر شرائح 650 جرام برطمان",                       nameEn: "Sliced Green Olives 650g – Jar",                    caseCount:  6, pricePerPiece: 118.11,  pricePerCarton: 708.69,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "39", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اخضر شرائح 3 كجم صفيحة",                           nameEn: "Sliced Green Olives 3kg – Tin",                     caseCount:  6, pricePerPiece: 406.53,  pricePerCarton: 2439.17,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "40", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اخضر 16 كيلو جردل",                                nameEn: "Green Olives 16kg – Pail",                          caseCount:  1, pricePerPiece: 1370.86, pricePerCarton: 1370.86,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "41", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اسود 650 جم برطمان",                               nameEn: "Black Olives 650g – Jar",                           caseCount:  6, pricePerPiece: 113.23,  pricePerCarton: 679.38,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "42", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اسود 1 كيلو برطمان",                               nameEn: "Black Olives 1kg – Jar",                            caseCount:  6, pricePerPiece: 163.55,  pricePerCarton: 981.31,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "43", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اسود شرائح مؤكسد 650 جرام برطمان",                 nameEn: "Sliced Oxidized Black Olives 650g – Jar",           caseCount:  6, pricePerPiece: 125.49,  pricePerCarton: 752.97,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "44", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اسود شرائح مؤكسد 3 كيلو صفيحة",                   nameEn: "Sliced Oxidized Black Olives 3kg – Tin",            caseCount:  6, pricePerPiece: 404.07,  pricePerCarton: 2424.41,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "45", brand: "Wadifood", category: "Olives",       nameAr: "زيتون اسود حجم كبير 16 كجم جردل",                        nameEn: "Large Black Olives 16kg – Pail",                    caseCount:  1, pricePerPiece: 1857.49, pricePerCarton: 1857.49,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "46", brand: "Wadifood", category: "Olives",       nameAr: "زيتون دولسى 16 كجم جردل",                                nameEn: "Dolce Olives 16kg – Pail",                          caseCount:  1, pricePerPiece: 692.23,  pricePerCarton: 692.23,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "47", brand: "Wadifood", category: "Olives",       nameAr: "زيتون كلاماتا 650 جرام برطمان",                          nameEn: "Kalamata Olives 650g – Jar",                        caseCount:  6, pricePerPiece: 124.95,  pricePerCarton: 749.72,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "48", brand: "Wadifood", category: "Olives",       nameAr: "زيتون كلاماتا مخلى 650 جرام برطمان",                     nameEn: "Marinated Kalamata Olives 650g – Jar",              caseCount:  6, pricePerPiece: 153.00,  pricePerCarton: 918.00,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "49", brand: "Wadifood", category: "Olives",       nameAr: "زيتون كلاماتا 1 كيلو برطمان",                            nameEn: "Kalamata Olives 1kg – Jar",                         caseCount:  6, pricePerPiece: 172.25,  pricePerCarton: 1033.52,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "50", brand: "Wadifood", category: "Olives",       nameAr: "زيتون كلاماتا مخلى 3 كجم برميل",                         nameEn: "Marinated Kalamata Olives 3kg – Barrel",            caseCount:  6, pricePerPiece: 581.38,  pricePerCarton: 3488.28,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "51", brand: "Wadifood", category: "Olives",       nameAr: "زيتون كلاماتا 16 كيلو جردل",                             nameEn: "Kalamata Olives 16kg – Pail",                       caseCount:  1, pricePerPiece: 2164.36, pricePerCarton: 2164.36,  hasTax: false, image: "/placeholder-product.svg" },

  // ─── WADIFOOD — Pickles ─────────────────────────────────────────────────────
  { id: "52", brand: "Wadifood", category: "Pickles",      nameAr: "مخلل مشكل 650 جم برطمان",                                nameEn: "Mixed Pickles 650g – Jar",                          caseCount:  6, pricePerPiece: 31.47,   pricePerCarton: 188.83,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "53", brand: "Wadifood", category: "Pickles",      nameAr: "ليمون مخلل 650 جم برطمان",                               nameEn: "Pickled Lemon 650g – Jar",                          caseCount:  6, pricePerPiece: 37.36,   pricePerCarton: 224.14,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "54", brand: "Wadifood", category: "Pickles",      nameAr: "فلفل مكسيكى مخلل 650 جم برطمان",                         nameEn: "Pickled Mexican Peppers 650g – Jar",                caseCount:  6, pricePerPiece: 38.79,   pricePerCarton: 232.76,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "55", brand: "Wadifood", category: "Pickles",      nameAr: "مخلل مشكل 1 كجم",                                        nameEn: "Mixed Pickles 1kg",                                 caseCount:  6, pricePerPiece: 45.28,   pricePerCarton: 271.66,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "56", brand: "Wadifood", category: "Pickles",      nameAr: "مخلل مشكل بوليفي 1 كجم برطمان",                          nameEn: "Bolivian Mixed Pickles 1kg – Jar",                  caseCount:  6, pricePerPiece: 37.41,   pricePerCarton: 224.48,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "57", brand: "Wadifood", category: "Pickles",      nameAr: "مخلل مشكل 4 كجم جردل",                                   nameEn: "Mixed Pickles 4kg – Pail",                          caseCount:  4, pricePerPiece: 78.86,   pricePerCarton: 315.45,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "58", brand: "Wadifood", category: "Pickles",      nameAr: "مخلل مشكل 3.78 كجم برطمان بلاستيك",                     nameEn: "Mixed Pickles 3.78kg – Plastic Jar",                caseCount:  4, pricePerPiece: 82.36,   pricePerCarton: 329.43,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "59", brand: "Wadifood", category: "Pickles",      nameAr: "هالبينو شرائح 3.78 كجم",                                 nameEn: "Sliced Jalapeños 3.78kg",                           caseCount:  4, pricePerPiece: 115.43,  pricePerCarton: 461.70,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "60", brand: "Wadifood", category: "Pickles",      nameAr: "مخلل مشكل فاخر 16 كجم جردل",                             nameEn: "Premium Mixed Pickles 16kg – Pail",                 caseCount:  1, pricePerPiece: 354.86,  pricePerCarton: 354.86,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "61", brand: "Wadifood", category: "Pickles",      nameAr: "هالبينو شرائح 1 كجم برطمان",                             nameEn: "Sliced Jalapeños 1kg – Jar",                        caseCount:  6, pricePerPiece: 50.34,   pricePerCarton: 302.07,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "62", brand: "Wadifood", category: "Pickles",      nameAr: "زيتون اخضر شرائح 1.6 كجم باوتش",                         nameEn: "Sliced Green Olives 1.6kg – Pouch",                 caseCount: 10, pricePerPiece: 188.24,  pricePerCarton: 1882.35,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "63", brand: "Wadifood", category: "Pickles",      nameAr: "زيتون اسود شرائح مؤكسد 1.6 كجم باوتش",                  nameEn: "Sliced Oxidized Black Olives 1.6kg – Pouch",        caseCount: 10, pricePerPiece: 176.47,  pricePerCarton: 1764.71,  hasTax: false, image: "/placeholder-product.svg" },

  // ─── KNORR — Seasonings ─────────────────────────────────────────────────────
  { id: "64", brand: "Knorr",    category: "Seasonings",   nameAr: "مرقة دجاج بودر كنور 1 كيلو",                             nameEn: "Knorr Chicken Powder Broth 1kg",                    caseCount:  6, pricePerPiece: 206.45,  pricePerCarton: 1238.70,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "65", brand: "Knorr",    category: "Seasonings",   nameAr: "مرقة دجاج مكعبات كنور 120 مكعب",                         nameEn: "Knorr Chicken Cube Broth 120-Cube Pack",            caseCount:  6, pricePerPiece: 164.67,  pricePerCarton: 988.02,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "66", brand: "Knorr",    category: "Seasonings",   nameAr: "مرقة لحم كنور 1 كيلو",                                   nameEn: "Knorr Beef Broth 1kg",                              caseCount:  6, pricePerPiece: 233.27,  pricePerCarton: 1399.62,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "67", brand: "Knorr",    category: "Seasonings",   nameAr: "مرقة خضار كنور 1 كيلو",                                  nameEn: "Knorr Vegetable Broth 1kg",                         caseCount:  6, pricePerPiece: 167.07,  pricePerCarton: 1002.42,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "68", brand: "Knorr",    category: "Seasonings",   nameAr: "مرقة سمك كنور 1 كيلو",                                   nameEn: "Knorr Fish Broth 1kg",                              caseCount:  6, pricePerPiece: 244.20,  pricePerCarton: 1465.20,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "69", brand: "Knorr",    category: "Seasonings",   nameAr: "ديمي جلاس كنور 750 جرام",                                nameEn: "Knorr Demi-Glace 750g",                             caseCount:  6, pricePerPiece: 348.93,  pricePerCarton: 2093.58,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "70", brand: "Knorr",    category: "Seasonings",   nameAr: "توابل شرق اقصى كنور 800 جرام",                           nameEn: "Knorr Far East Spices 800g",                        caseCount:  6, pricePerPiece: 299.81,  pricePerCarton: 1798.84,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "71", brand: "Knorr",    category: "Seasonings",   nameAr: "توابل دواجن كنور 1 كيلو",                                nameEn: "Knorr Poultry Spices 1kg",                          caseCount:  6, pricePerPiece: 440.61,  pricePerCarton: 2643.68,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "72", brand: "Knorr",    category: "Seasonings",   nameAr: "توابل شواء كنور 900 جرام",                               nameEn: "Knorr Grill Spices 900g",                           caseCount:  6, pricePerPiece: 485.98,  pricePerCarton: 2915.89,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "73", brand: "Knorr",    category: "Seasonings",   nameAr: "شوربة كريمة دجاج كنور 720 جرام",                         nameEn: "Knorr Cream of Chicken Soup 720g",                  caseCount:  6, pricePerPiece: 324.58,  pricePerCarton: 1947.47,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "74", brand: "Knorr",    category: "Seasonings",   nameAr: "شوربة كريمة مشروم كنور 700 جرام",                        nameEn: "Knorr Cream of Mushroom Soup 700g",                 caseCount:  6, pricePerPiece: 344.46,  pricePerCarton: 2066.74,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "75", brand: "Knorr",    category: "Seasonings",   nameAr: "بطاطس مهروسة كنور 2 كيلو",                               nameEn: "Knorr Mashed Potato 2kg",                           caseCount:  1, pricePerPiece: 962.81,  pricePerCarton: 962.81,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "76", brand: "Knorr",    category: "Seasonings",   nameAr: "مرقة دجاج بودر ماجي 1 كيلو",                             nameEn: "Maggi Chicken Powder Broth 1kg",                    caseCount:  6, pricePerPiece: 177.06,  pricePerCarton: 1062.36,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "77", brand: "Knorr",    category: "Seasonings",   nameAr: "مرقة لحم بودر ماجي 1 كيلو",                              nameEn: "Maggi Beef Powder Broth 1kg",                       caseCount:  6, pricePerPiece: 205.86,  pricePerCarton: 1235.16,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "78", brand: "Knorr",    category: "Seasonings",   nameAr: "مرقة دجاج مكعب ماجي 120 مكعب",                           nameEn: "Maggi Chicken Cube Broth 120-Cube Pack",            caseCount:  6, pricePerPiece: 149.64,  pricePerCarton: 897.84,   hasTax: false, image: "/placeholder-product.svg" },

  // ─── HEINZ — Sauces ─────────────────────────────────────────────────────────
  { id: "79",  brand: "Heinz",   category: "Sauces",       nameAr: "باربكيو 4.25 كيلو هاينز",                                nameEn: "Heinz BBQ Sauce 4.25kg",                            caseCount:  4, pricePerPiece: 315.79,  pricePerCarton: 1263.16,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "80",  brand: "Heinz",   category: "Sauces",       nameAr: "باربكيو 200 جرام هاينز",                                 nameEn: "Heinz BBQ Sauce 200g",                              caseCount: 24, pricePerPiece: 45.76,   pricePerCarton: 1098.32,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "81",  brand: "Heinz",   category: "Sauces",       nameAr: "خل 1 لتر هاينز",                                         nameEn: "Heinz Vinegar 1L",                                  caseCount: 12, pricePerPiece: 17.15,   pricePerCarton: 205.79,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "82",  brand: "Heinz",   category: "Sauces",       nameAr: "شيلي صوص 195 جرام هاينز",                                nameEn: "Heinz Chilli Sauce 195g",                           caseCount: 24, pricePerPiece: 45.76,   pricePerCarton: 1098.32,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "83",  brand: "Heinz",   category: "Sauces",       nameAr: "صلصة برطمان 360 جرام هاينز",                             nameEn: "Heinz Tomato Sauce 360g – Jar",                     caseCount: 12, pricePerPiece: 30.78,   pricePerCarton: 369.37,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "84",  brand: "Heinz",   category: "Sauces",       nameAr: "صوص حار 165 جرام هاينز",                                 nameEn: "Heinz Hot Sauce 165g",                              caseCount: 24, pricePerPiece: 36.61,   pricePerCarton: 878.74,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "85",  brand: "Heinz",   category: "Sauces",       nameAr: "كاتشب ظرف 7 جرام – 1000 ظرف هاينز",                     nameEn: "Heinz Ketchup Sachets 7g – 1000 pcs",               caseCount: 1000, pricePerPiece: 0.42,  pricePerCarton: 423.68,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "86",  brand: "Heinz",   category: "Sauces",       nameAr: "كاتشب 10 كيلو هاينز",                                   nameEn: "Heinz Ketchup 10kg",                                caseCount:  1, pricePerPiece: 482.46,  pricePerCarton: 482.46,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "87",  brand: "Heinz",   category: "Sauces",       nameAr: "كاتشب 4.25 كيلو هاينز",                                 nameEn: "Heinz Ketchup 4.25kg",                              caseCount:  4, pricePerPiece: 232.46,  pricePerCarton: 929.82,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "88",  brand: "Heinz",   category: "Sauces",       nameAr: "كاتشب 295 جرام هاينز",                                  nameEn: "Heinz Ketchup 295g",                                caseCount: 12, pricePerPiece: 45.76,   pricePerCarton: 549.16,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "89",  brand: "Heinz",   category: "Sauces",       nameAr: "كاتشب 195 جرام هاينز",                                  nameEn: "Heinz Ketchup 195g",                                caseCount: 24, pricePerPiece: 34.32,   pricePerCarton: 823.79,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "90",  brand: "Heinz",   category: "Sauces",       nameAr: "مايونيز كلاسيك 3 كيلو هاينز",                           nameEn: "Heinz Classic Mayonnaise 3kg",                      caseCount:  4, pricePerPiece: 350.88,  pricePerCarton: 1403.51,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "91",  brand: "Heinz",   category: "Sauces",       nameAr: "مسطردة بلاستيك 235 جرام هاينز",                         nameEn: "Heinz Mustard Plastic 235g",                        caseCount: 12, pricePerPiece: 39.68,   pricePerCarton: 476.11,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "92",  brand: "Heinz",   category: "Sauces",       nameAr: "مسطردة 3.90 كيلو هاينز",                                nameEn: "Heinz Mustard 3.90kg",                              caseCount:  4, pricePerPiece: 320.18,  pricePerCarton: 1280.70,  hasTax: true,  image: "/placeholder-product.svg" },
  { id: "93",  brand: "Heinz",   category: "Sauces",       nameAr: "هريسة شطة 170 جرام هاينز",                              nameEn: "Heinz Harissa Chili 170g",                          caseCount: 12, pricePerPiece: 29.11,   pricePerCarton: 349.26,   hasTax: true,  image: "/placeholder-product.svg" },

  // ─── JUHAYNNA — Milk ────────────────────────────────────────────────────────
  { id: "94",  brand: "Juhaynna", category: "Milk",        nameAr: "جهينة حليب 1 لتر",                                       nameEn: "Juhaynna Milk 1L",                                  caseCount: 12, pricePerPiece: 52.33,   pricePerCarton: 627.96,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "95",  brand: "Juhaynna", category: "Milk",        nameAr: "جهينة حليب 1.5 لتر",                                     nameEn: "Juhaynna Milk 1.5L",                                caseCount:  8, pricePerPiece: 73.50,   pricePerCarton: 588.00,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "96",  brand: "Juhaynna", category: "Milk",        nameAr: "جهينة كريمة خفق 5 كيلو",                                 nameEn: "Juhaynna Whipping Cream 5kg",                       caseCount:  1, pricePerPiece: 985.94,  pricePerCarton: 985.94,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "97",  brand: "Juhaynna", category: "Milk",        nameAr: "جهينة كريمة خفق 1 لتر",                                  nameEn: "Juhaynna Whipping Cream 1L",                        caseCount: 12, pricePerPiece: 272.00,  pricePerCarton: 3264.00,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "98",  brand: "Juhaynna", category: "Milk",        nameAr: "جهينة كريمة طهي 1 لتر",                                  nameEn: "Juhaynna Cooking Cream 1L",                         caseCount: 12, pricePerPiece: 272.00,  pricePerCarton: 3264.00,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "99",  brand: "Juhaynna", category: "Milk",        nameAr: "بخيرة حليب 1 لتر",                                       nameEn: "Bakhira Milk 1L",                                   caseCount: 12, pricePerPiece: 40.63,   pricePerCarton: 487.56,   hasTax: false, image: "/placeholder-product.svg" },

  // ─── LAMAR — Milk ───────────────────────────────────────────────────────────
  { id: "112", brand: "lamar",   category: "Milk",         nameAr: "لمار 1 لتر",                                             nameEn: "Lamar Milk 1L",                                     caseCount: 12, pricePerPiece: 45.45,   pricePerCarton: 545.45,   hasTax: false, image: "/placeholder-product.svg" },

  // ─── SAVOLA — Pasta ─────────────────────────────────────────────────────────
  { id: "113", brand: "savola",  category: "Pasta",        nameAr: "مكرونة الملكة 400 جرام",                                 nameEn: "Al-Maleka Pasta 400g",                              caseCount: 20, pricePerPiece: 13.95,   pricePerCarton: 278.95,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "114", brand: "savola",  category: "Pasta",        nameAr: "مكرونة الملكة 1000 جرام",                                nameEn: "Al-Maleka Pasta 1000g",                             caseCount: 10, pricePerPiece: 32.63,   pricePerCarton: 326.32,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "115", brand: "savola",  category: "Pasta",        nameAr: "مكرونة الملكة لازانيا",                                  nameEn: "Al-Maleka Lasagna",                                 caseCount: 10, pricePerPiece: 27.37,   pricePerCarton: 273.68,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "116", brand: "savola",  category: "Pasta",        nameAr: "مكرونة مكرونتو 350 جرام",                                nameEn: "Macaronito Pasta 350g",                             caseCount: 20, pricePerPiece: 9.11,    pricePerCarton: 182.11,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "117", brand: "savola",  category: "Pasta",        nameAr: "مكرونة مكرونتو 10 كيلو",                                 nameEn: "Macaronito Pasta 10kg",                             caseCount:  1, pricePerPiece: 231.58,  pricePerCarton: 231.58,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "118", brand: "savola",  category: "Pasta",        nameAr: "مكرونة ايطاليانو 400 جرام",                              nameEn: "Italiano Pasta 400g",                               caseCount: 20, pricePerPiece: 21.31,   pricePerCarton: 426.13,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "119", brand: "savola",  category: "Pasta",        nameAr: "مكرونة ايطاليانو 1000 جرام",                             nameEn: "Italiano Pasta 1000g",                              caseCount: 10, pricePerPiece: 45.71,   pricePerCarton: 457.06,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "120", brand: "savola",  category: "Pasta",        nameAr: "مكرونة ايطاليانو لازانيا",                               nameEn: "Italiano Lasagna",                                  caseCount: 10, pricePerPiece: 34.90,   pricePerCarton: 349.03,   hasTax: true,  image: "/placeholder-product.svg" },
  { id: "121", brand: "savola",  category: "Pasta",        nameAr: "مكرونة ايطاليانو بيج شيل / كانيلون",                     nameEn: "Italiano Jumbo Shell / Cannelloni",                 caseCount: 10, pricePerPiece: 33.15,   pricePerCarton: 331.49,   hasTax: true,  image: "/placeholder-product.svg" },

  // ─── SAVOLA — Cooking Oils ──────────────────────────────────────────────────
  { id: "122", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية ذرة 0.700 لتر",                                   nameEn: "Afia Corn Oil 0.700L",                              caseCount:  6, pricePerPiece: 94.48,   pricePerCarton: 566.91,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "123", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية ذرة 1.6 لتر",                                     nameEn: "Afia Corn Oil 1.6L",                                caseCount:  6, pricePerPiece: 209.90,  pricePerCarton: 1259.38,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "124", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية ذرة 2.2 لتر",                                     nameEn: "Afia Corn Oil 2.2L",                                caseCount:  4, pricePerPiece: 283.19,  pricePerCarton: 1132.77,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "125", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية بلس 0.700 لتر",                                   nameEn: "Afia Plus Oil 0.700L",                              caseCount:  6, pricePerPiece: 89.58,   pricePerCarton: 537.47,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "126", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية بلس 1.6 لتر",                                     nameEn: "Afia Plus Oil 1.6L",                                caseCount:  6, pricePerPiece: 200.13,  pricePerCarton: 1200.77,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "127", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية بلس 2.2 لتر",                                     nameEn: "Afia Plus Oil 2.2L",                                caseCount:  4, pricePerPiece: 268.54,  pricePerCarton: 1074.15,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "128", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية عباد 0.700 لتر",                                  nameEn: "Afia Sunflower Oil 0.700L",                         caseCount:  6, pricePerPiece: 76.55,   pricePerCarton: 459.31,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "129", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية عباد 1.6 لتر",                                    nameEn: "Afia Sunflower Oil 1.6L",                           caseCount:  6, pricePerPiece: 171.86,  pricePerCarton: 1031.16,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "130", brand: "savola",  category: "Cooking Oil",  nameAr: "عافية عباد 2.2 لتر",                                    nameEn: "Afia Sunflower Oil 2.2L",                           caseCount:  4, pricePerPiece: 234.47,  pricePerCarton: 937.89,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "131", brand: "savola",  category: "Cooking Oil",  nameAr: "سلايت عباد 0.675 لتر",                                  nameEn: "Slite Sunflower Oil 0.675L",                        caseCount: 12, pricePerPiece: 71.32,   pricePerCarton: 855.83,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "132", brand: "savola",  category: "Cooking Oil",  nameAr: "سلايت عباد 1.5 لتر",                                    nameEn: "Slite Sunflower Oil 1.5L",                          caseCount:  6, pricePerPiece: 157.18,  pricePerCarton: 943.11,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "133", brand: "savola",  category: "Cooking Oil",  nameAr: "سلايت عباد 2.1 لتر",                                    nameEn: "Slite Sunflower Oil 2.1L",                          caseCount:  4, pricePerPiece: 214.93,  pricePerCarton: 859.74,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "134", brand: "savola",  category: "Cooking Oil",  nameAr: "حلوة 0.700 لتر",                                        nameEn: "Helwa Oil 0.700L",                                  caseCount: 12, pricePerPiece: 63.44,   pricePerCarton: 761.26,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "135", brand: "savola",  category: "Cooking Oil",  nameAr: "حلوة 1 لتر",                                            nameEn: "Helwa Oil 1L",                                      caseCount: 12, pricePerPiece: 83.09,   pricePerCarton: 997.03,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "136", brand: "savola",  category: "Cooking Oil",  nameAr: "حلوة 2.25 لتر",                                         nameEn: "Helwa Oil 2.25L",                                   caseCount:  4, pricePerPiece: 183.54,  pricePerCarton: 734.16,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "137", brand: "savola",  category: "Cooking Oil",  nameAr: "حلوة 4.5 لتر",                                          nameEn: "Helwa Oil 4.5L",                                    caseCount:  2, pricePerPiece: 366.95,  pricePerCarton: 733.90,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "138", brand: "savola",  category: "Cooking Oil",  nameAr: "هنادي 0.700 لتر",                                       nameEn: "Hanadi Oil 0.700L",                                 caseCount: 12, pricePerPiece: 63.44,   pricePerCarton: 761.26,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "139", brand: "savola",  category: "Cooking Oil",  nameAr: "هنادي 1 لتر",                                           nameEn: "Hanadi Oil 1L",                                     caseCount: 12, pricePerPiece: 83.09,   pricePerCarton: 997.03,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "140", brand: "savola",  category: "Cooking Oil",  nameAr: "هنادي 2.1 لتر",                                         nameEn: "Hanadi Oil 2.1L",                                   caseCount:  4, pricePerPiece: 175.66,  pricePerCarton: 702.64,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "141", brand: "savola",  category: "Cooking Oil",  nameAr: "روابي / جنة 0.700 كجم",                                 nameEn: "Rawabi / Jana Oil 0.700kg",                         caseCount:  8, pricePerPiece: 92.58,   pricePerCarton: 740.68,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "142", brand: "savola",  category: "Cooking Oil",  nameAr: "روابي / جنة 1.5 كجم",                                  nameEn: "Rawabi / Jana Oil 1.5kg",                           caseCount:  4, pricePerPiece: 180.61,  pricePerCarton: 722.44,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "143", brand: "savola",  category: "Cooking Oil",  nameAr: "روابي / جنة 2.5 كجم",                                  nameEn: "Rawabi / Jana Oil 2.5kg",                           caseCount:  4, pricePerPiece: 283.52,  pricePerCarton: 1134.07,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "144", brand: "savola",  category: "Cooking Oil",  nameAr: "روابي / جنة 4.25 كجم",                                 nameEn: "Rawabi / Jana Oil 4.25kg",                          caseCount:  1, pricePerPiece: 483.54,  pricePerCarton: 483.54,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "145", brand: "savola",  category: "Cooking Oil",  nameAr: "روابي / جنة 11 كجم",                                   nameEn: "Rawabi / Jana Oil 11kg",                            caseCount:  1, pricePerPiece: 1233.85, pricePerCarton: 1233.85,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "146", brand: "savola",  category: "Cooking Oil",  nameAr: "شمس باكيت 1.45 كجم",                                   nameEn: "Shams Packet Oil 1.45kg",                           caseCount:  4, pricePerPiece: 154.82,  pricePerCarton: 619.27,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "147", brand: "savola",  category: "Cooking Oil",  nameAr: "شمس 11 كجم",                                            nameEn: "Shams Oil 11kg",                                    caseCount:  1, pricePerPiece: 1131.58, pricePerCarton: 1131.58,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "148", brand: "savola",  category: "Cooking Oil",  nameAr: "الطاهي / شمس 1.3 كجم",                                 nameEn: "Al-Tahi / Shams Oil 1.3kg",                         caseCount:  6, pricePerPiece: 138.08,  pricePerCarton: 828.47,   hasTax: false, image: "/placeholder-product.svg" },
  { id: "149", brand: "savola",  category: "Cooking Oil",  nameAr: "جنة مكس 1 كجم",                                        nameEn: "Jana Mix Oil 1kg",                                  caseCount: 10, pricePerPiece: 130.94,  pricePerCarton: 1309.41,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "150", brand: "savola",  category: "Cooking Oil",  nameAr: "زيت اولين الطاهي 20 لتر",                               nameEn: "Olein Al-Tahi Cooking Oil 20L",                     caseCount:  1, pricePerPiece: 1674.44, pricePerCarton: 1674.44,  hasTax: false, image: "/placeholder-product.svg" },
  { id: "151", brand: "savola",  category: "Cooking Oil",  nameAr: "زيت عباد الطاهي 20 لتر",                                nameEn: "Sunflower Al-Tahi Cooking Oil 20L",                 caseCount:  1, pricePerPiece: 2000.00, pricePerCarton: 2000.00,  hasTax: false, image: "/placeholder-product.svg" },

  // ─── PEPSI — Soft Drinks 1.5L PET ──────────────────────────────────────────
  { id: "152", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 1.5 لتر",              nameEn: "Pepsi 1.5L PET",                    caseCount:  6, pricePerPiece:  26.97, pricePerCarton:  161.85, hasTax: true, image: "/placeholder-product.svg" },
  { id: "153", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى دايت 1.5 لتر",         nameEn: "Pepsi Diet 1.5L PET",               caseCount:  6, pricePerPiece:  26.97, pricePerCarton:  161.85, hasTax: true, image: "/placeholder-product.svg" },
  { id: "154", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 1.5 لتر",             nameEn: "7UP 1.5L PET",                      caseCount:  6, pricePerPiece:  26.97, pricePerCarton:  161.85, hasTax: true, image: "/placeholder-product.svg" },
  { id: "155", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب فري 1.5 لتر",         nameEn: "7UP Free 1.5L PET",                 caseCount:  6, pricePerPiece:  26.97, pricePerCarton:  161.85, hasTax: true, image: "/placeholder-product.svg" },
  { id: "156", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 1.5 لتر",     nameEn: "Mirinda Orange 1.5L PET",           caseCount:  6, pricePerPiece:  26.97, pricePerCarton:  161.85, hasTax: true, image: "/placeholder-product.svg" },
  { id: "157", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا تفاح 1.5 لتر",       nameEn: "Mirinda Green Apple 1.5L PET",      caseCount:  6, pricePerPiece:  26.97, pricePerCarton:  161.85, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Soft Drinks 1L PET ────────────────────────────────────────────
  { id: "158", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 1 لتر",               nameEn: "Pepsi 1L PET",                      caseCount:  6, pricePerPiece:  19.10, pricePerCarton:  114.61, hasTax: true, image: "/placeholder-product.svg" },
  { id: "159", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 1 لتر",              nameEn: "7UP 1L PET",                        caseCount:  6, pricePerPiece:  19.10, pricePerCarton:  114.61, hasTax: true, image: "/placeholder-product.svg" },
  { id: "160", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 1 لتر",      nameEn: "Mirinda Orange 1L PET",             caseCount:  6, pricePerPiece:  19.10, pricePerCarton:  114.61, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Soft Drinks 2.5L PET ──────────────────────────────────────────
  { id: "161", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 2.5/2.43 لتر",        nameEn: "Pepsi 2.5L PET",                    caseCount:  6, pricePerPiece:  30.54, pricePerCarton:  183.21, hasTax: true, image: "/placeholder-product.svg" },
  { id: "162", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 2.5/2.43 لتر",       nameEn: "7UP 2.5L PET",                      caseCount:  6, pricePerPiece:  30.54, pricePerCarton:  183.21, hasTax: true, image: "/placeholder-product.svg" },
  { id: "163", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 2.5/2.43 لتر", nameEn: "Mirinda Orange 2.5L PET",         caseCount:  6, pricePerPiece:  30.54, pricePerCarton:  183.21, hasTax: true, image: "/placeholder-product.svg" },
  { id: "164", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا تفاح 2.5/2.43 لتر",  nameEn: "Mirinda Green Apple 2.5L PET",    caseCount:  6, pricePerPiece:  30.54, pricePerCarton:  183.21, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Soft Drinks 400ml PET ─────────────────────────────────────────
  { id: "165", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 400 مل بلاستيك",       nameEn: "Pepsi 400ml PET",                   caseCount: 12, pricePerPiece:   8.67, pricePerCarton:  104.09, hasTax: true, image: "/placeholder-product.svg" },
  { id: "166", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى دايت 400 مل بلاستيك",  nameEn: "Pepsi Diet 400ml PET",              caseCount: 12, pricePerPiece:   8.67, pricePerCarton:  104.09, hasTax: true, image: "/placeholder-product.svg" },
  { id: "167", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 400 مل بلاستيك",      nameEn: "7UP 400ml PET",                     caseCount: 12, pricePerPiece:   8.67, pricePerCarton:  104.09, hasTax: true, image: "/placeholder-product.svg" },
  { id: "168", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 400 مل بلاستيك", nameEn: "Mirinda Orange 400ml PET",       caseCount: 12, pricePerPiece:   8.67, pricePerCarton:  104.09, hasTax: true, image: "/placeholder-product.svg" },
  { id: "169", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا تفاح 400 مل بلاستيك",  nameEn: "Mirinda Green Apple 400ml PET",  caseCount: 12, pricePerPiece:   8.67, pricePerCarton:  104.09, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Soft Drinks 250ml PET ─────────────────────────────────────────
  { id: "170", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 250 مل بلاستيك",       nameEn: "Pepsi 250ml PET",                   caseCount: 12, pricePerPiece:   7.38, pricePerCarton:   88.59, hasTax: true, image: "/placeholder-product.svg" },
  { id: "171", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 250 مل بلاستيك",      nameEn: "7UP 250ml PET",                     caseCount: 12, pricePerPiece:   7.38, pricePerCarton:   88.59, hasTax: true, image: "/placeholder-product.svg" },
  { id: "172", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 250 مل بلاستيك", nameEn: "Mirinda Orange 250ml PET",       caseCount: 12, pricePerPiece:   7.38, pricePerCarton:   88.59, hasTax: true, image: "/placeholder-product.svg" },
  { id: "173", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا تفاح 250 مل بلاستيك",  nameEn: "Mirinda Green Apple 250ml PET",  caseCount: 12, pricePerPiece:   7.38, pricePerCarton:   88.59, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Cans 320ml ────────────────────────────────────────────────────
  { id: "174", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 320 مل كانز",          nameEn: "Pepsi 320ml Can",                   caseCount: 24, pricePerPiece:  11.44, pricePerCarton:  274.65, hasTax: true, image: "/placeholder-product.svg" },
  { id: "175", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى دايت 320 مل كانز",     nameEn: "Pepsi Diet 320ml Can",              caseCount: 24, pricePerPiece:  11.44, pricePerCarton:  274.65, hasTax: true, image: "/placeholder-product.svg" },
  { id: "176", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 320 مل كانز",         nameEn: "7UP 320ml Can",                     caseCount: 24, pricePerPiece:  11.44, pricePerCarton:  274.65, hasTax: true, image: "/placeholder-product.svg" },
  { id: "177", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب فري 320 مل كانز",     nameEn: "7UP Free 320ml Can",                caseCount: 24, pricePerPiece:  11.44, pricePerCarton:  274.65, hasTax: true, image: "/placeholder-product.svg" },
  { id: "178", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 320 مل كانز", nameEn: "Mirinda Orange 320ml Can",          caseCount: 24, pricePerPiece:  11.44, pricePerCarton:  274.65, hasTax: true, image: "/placeholder-product.svg" },
  { id: "179", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا تفاح 320 مل كانز",   nameEn: "Mirinda Green Apple 320ml Can",     caseCount: 24, pricePerPiece:  11.44, pricePerCarton:  274.65, hasTax: true, image: "/placeholder-product.svg" },
  { id: "180", brand: "Pepsi", category: "Soft Drinks", nameAr: "ماونتن ديو 320 مل كانز",     nameEn: "Mountain Dew 320ml Can",            caseCount: 24, pricePerPiece:  11.44, pricePerCarton:  274.65, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Special Flavour 320ml Cans ────────────────────────────────────
  { id: "181", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى فراولة 320 مل كانز",   nameEn: "Pepsi Strawberry 320ml Can",        caseCount: 24, pricePerPiece:   6.06, pricePerCarton:  145.45, hasTax: true, image: "/placeholder-product.svg" },
  { id: "182", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى كريم صودا 320 مل كانز", nameEn: "Pepsi Cream Soda 320ml Can",       caseCount: 24, pricePerPiece:   6.06, pricePerCarton:  145.45, hasTax: true, image: "/placeholder-product.svg" },
  { id: "183", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى توت 320 مل كانز",      nameEn: "Pepsi Black Raspberry 320ml Can",   caseCount: 24, pricePerPiece:   6.06, pricePerCarton:  145.45, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Cans 240ml ────────────────────────────────────────────────────
  { id: "184", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 240 مل كانز",          nameEn: "Pepsi 240ml Can",                   caseCount: 24, pricePerPiece:  10.80, pricePerCarton:  259.16, hasTax: true, image: "/placeholder-product.svg" },
  { id: "185", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 240 مل كانز",         nameEn: "7UP 240ml Can",                     caseCount: 24, pricePerPiece:  10.80, pricePerCarton:  259.16, hasTax: true, image: "/placeholder-product.svg" },
  { id: "186", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 240 مل كانز", nameEn: "Mirinda Orange 240ml Can",          caseCount: 24, pricePerPiece:  10.80, pricePerCarton:  259.16, hasTax: true, image: "/placeholder-product.svg" },
  { id: "187", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا تفاح 240 مل كانز",   nameEn: "Mirinda Green Apple 240ml Can",     caseCount: 24, pricePerPiece:  10.80, pricePerCarton:  259.16, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Glass NRB 350ml ───────────────────────────────────────────────
  { id: "188", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 350 مل زجاج",          nameEn: "Pepsi 350ml Glass NRB",             caseCount: 12, pricePerPiece:   8.88, pricePerCarton:  106.52, hasTax: true, image: "/placeholder-product.svg" },
  { id: "189", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 350 مل زجاج",         nameEn: "7UP 350ml Glass NRB",               caseCount: 12, pricePerPiece:   8.88, pricePerCarton:  106.52, hasTax: true, image: "/placeholder-product.svg" },
  { id: "190", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 350 مل زجاج", nameEn: "Mirinda Orange 350ml Glass NRB",    caseCount: 12, pricePerPiece:   8.88, pricePerCarton:  106.52, hasTax: true, image: "/placeholder-product.svg" },
  { id: "191", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا تفاح 350 مل زجاج",   nameEn: "Mirinda Green Apple 350ml Glass NRB", caseCount: 12, pricePerPiece: 8.88, pricePerCarton:  106.52, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — Glass NRB 300ml ───────────────────────────────────────────────
  { id: "192", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى 300 مل زجاج",          nameEn: "Pepsi 300ml Glass NRB",             caseCount: 12, pricePerPiece:  11.31, pricePerCarton:  135.76, hasTax: true, image: "/placeholder-product.svg" },
  { id: "193", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسى دايت 300 مل زجاج",     nameEn: "Pepsi Diet 300ml Glass NRB",        caseCount: 12, pricePerPiece:  11.31, pricePerCarton:  135.76, hasTax: true, image: "/placeholder-product.svg" },
  { id: "194", brand: "Pepsi", category: "Soft Drinks", nameAr: "سفن اب 300 مل زجاج",         nameEn: "7UP 300ml Glass NRB",               caseCount: 12, pricePerPiece:  11.31, pricePerCarton:  135.76, hasTax: true, image: "/placeholder-product.svg" },
  { id: "195", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا برتقال 300 مل زجاج", nameEn: "Mirinda Orange 300ml Glass NRB",    caseCount: 12, pricePerPiece:  11.31, pricePerCarton:  135.76, hasTax: true, image: "/placeholder-product.svg" },
  { id: "196", brand: "Pepsi", category: "Soft Drinks", nameAr: "ميريندا تفاح 300 مل زجاج",   nameEn: "Mirinda Green Apple 300ml Glass NRB", caseCount: 12, pricePerPiece: 11.31, pricePerCarton:  135.76, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI FIZZ ─────────────────────────────────────────────────────────────
  { id: "197", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسي فيز 1.5 لتر",          nameEn: "Pepsi Fizz 1.5L",                   caseCount:  6, pricePerPiece:  11.18, pricePerCarton:   67.10, hasTax: true, image: "/placeholder-product.svg" },
  { id: "198", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسي فيز 2.5/2.43 لتر",     nameEn: "Pepsi Fizz 2.5L",                   caseCount:  6, pricePerPiece:  15.08, pricePerCarton:   90.47, hasTax: true, image: "/placeholder-product.svg" },
  { id: "199", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسي فيز 400 مل",            nameEn: "Pepsi Fizz 400ml PET",              caseCount: 12, pricePerPiece:   3.85, pricePerCarton:   46.23, hasTax: true, image: "/placeholder-product.svg" },
  { id: "200", brand: "Pepsi", category: "Soft Drinks", nameAr: "بيبسي فيز 250 مل",            nameEn: "Pepsi Fizz 250ml PET",              caseCount: 12, pricePerPiece:   3.64, pricePerCarton:   43.73, hasTax: true, image: "/placeholder-product.svg" },

  // ─── EXTRA FIZZ ─────────────────────────────────────────────────────────────
  { id: "201", brand: "Pepsi", category: "Soft Drinks", nameAr: "اكسترا فيز 2.5 لتر",         nameEn: "Extra Fizz 2.5L",                   caseCount:  6, pricePerPiece:  22.70, pricePerCarton:  136.20, hasTax: true, image: "/placeholder-product.svg" },
  { id: "202", brand: "Pepsi", category: "Soft Drinks", nameAr: "اكسترا فيز 1.5 لتر",         nameEn: "Extra Fizz 1.5L",                   caseCount:  6, pricePerPiece:  18.81, pricePerCarton:  112.83, hasTax: true, image: "/placeholder-product.svg" },
  { id: "203", brand: "Pepsi", category: "Soft Drinks", nameAr: "اكسترا فيز 750 مل",           nameEn: "Extra Fizz 750ml PET",              caseCount:  6, pricePerPiece:  11.18, pricePerCarton:   67.10, hasTax: true, image: "/placeholder-product.svg" },
  { id: "204", brand: "Pepsi", category: "Soft Drinks", nameAr: "اكسترا فيز 400 مل",           nameEn: "Extra Fizz 400ml PET",              caseCount: 12, pricePerPiece:   7.29, pricePerCarton:   87.47, hasTax: true, image: "/placeholder-product.svg" },
  { id: "205", brand: "Pepsi", category: "Soft Drinks", nameAr: "اكسترا فيز 250 مل",           nameEn: "Extra Fizz 250ml PET",              caseCount: 12, pricePerPiece:   6.89, pricePerCarton:   82.72, hasTax: true, image: "/placeholder-product.svg" },

  // ─── TONIC WATER ────────────────────────────────────────────────────────────
  { id: "206", brand: "Pepsi", category: "Tonic Water", nameAr: "ايفرفيس تونيك 1 لتر",        nameEn: "Tonic Water 1L PET",                caseCount:  6, pricePerPiece:  24.31, pricePerCarton:  145.85, hasTax: true, image: "/placeholder-product.svg" },
  { id: "207", brand: "Pepsi", category: "Tonic Water", nameAr: "ايفرفيس تونيك 250 مل كانز",  nameEn: "Tonic Water 250ml Can",             caseCount: 24, pricePerPiece:  12.50, pricePerCarton:  300.00, hasTax: true, image: "/placeholder-product.svg" },

  // ─── STING ENERGY ───────────────────────────────────────────────────────────
  { id: "208", brand: "Pepsi", category: "Energy Drinks", nameAr: "ستينج 275 مل زجاج",        nameEn: "Sting Energy 275ml NRB",            caseCount: 12, pricePerPiece:   7.88, pricePerCarton:   94.53, hasTax: true, image: "/placeholder-product.svg" },
  { id: "209", brand: "Pepsi", category: "Energy Drinks", nameAr: "ستينج 400 مل بلاستيك",     nameEn: "Sting Energy 400ml PET",            caseCount: 12, pricePerPiece:   8.96, pricePerCarton:  107.52, hasTax: true, image: "/placeholder-product.svg" },

  // ─── AQUAFINA — Water ───────────────────────────────────────────────────────
  { id: "210", brand: "Pepsi", category: "Water",        nameAr: "اكوافينا 330 مل",            nameEn: "Aquafina 330ml",                    caseCount: 20, pricePerPiece:   3.29, pricePerCarton:   65.79, hasTax: true, image: "/placeholder-product.svg" },
  { id: "211", brand: "Pepsi", category: "Water",        nameAr: "اكوافينا 600 مل",            nameEn: "Aquafina 600ml",                    caseCount: 20, pricePerPiece:   4.12, pricePerCarton:   82.46, hasTax: true, image: "/placeholder-product.svg" },
  { id: "212", brand: "Pepsi", category: "Water",        nameAr: "اكوافينا 1.5 لتر",           nameEn: "Aquafina 1.5L",                     caseCount: 12, pricePerPiece:   6.87, pricePerCarton:   82.46, hasTax: true, image: "/placeholder-product.svg" },
  { id: "213", brand: "Pepsi", category: "Water",        nameAr: "اكوافينا جالون 18.9 لتر",    nameEn: "Aquafina Gallon 18.9L",             caseCount:  1, pricePerPiece:  71.93, pricePerCarton:   71.93, hasTax: true, image: "/placeholder-product.svg" },
  { id: "214", brand: "Pepsi", category: "Water",        nameAr: "اكوافينا سباركلينج 250 مل",  nameEn: "Aquafina Sparkling 250ml Can",      caseCount: 12, pricePerPiece:  11.56, pricePerCarton:  138.70, hasTax: true, image: "/placeholder-product.svg" },

  // ─── PEPSI — BIB Syrup ──────────────────────────────────────────────────────
  { id: "215", brand: "Pepsi", category: "BIB Syrup",    nameAr: "باجن بوكس",                  nameEn: "BIB Bag-in-Box Syrup",              caseCount:  1, pricePerPiece: 1624.43, pricePerCarton: 1624.43, hasTax: true, image: "/placeholder-product.svg" },

  // ─── FAYROUZ / ABC — Malt Beverages ─────────────────────────────────────────
  { id: "216", brand: "Fayrouz", category: "Malt Beverages", nameAr: "فيروز أناناس 330 مل كانز",     nameEn: "Fayrouz Pineapple 330ml Can",   caseCount: 24, pricePerPiece:  10.50, pricePerCarton:  252.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "217", brand: "Fayrouz", category: "Malt Beverages", nameAr: "فيروز مانجو وخوخ 330 مل كانز", nameEn: "Fayrouz Mango & Peach 330ml Can", caseCount: 24, pricePerPiece: 9.50, pricePerCarton:  228.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "218", brand: "Fayrouz", category: "Malt Beverages", nameAr: "بيريل 330 مل كانز",           nameEn: "Birel 330ml Can",               caseCount: 24, pricePerPiece:  10.50, pricePerCarton:  252.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "219", brand: "Fayrouz", category: "Malt Beverages", nameAr: "امستل زيرو 330 مل كانز",      nameEn: "Amstel Zero 330ml Can",         caseCount: 24, pricePerPiece:   9.50, pricePerCarton:  228.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "220", brand: "Fayrouz", category: "Malt Beverages", nameAr: "امستل ليمون 330 مل كانز",     nameEn: "Amstel Lemon 330ml Can",        caseCount: 24, pricePerPiece:   9.50, pricePerCarton:  228.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "221", brand: "Fayrouz", category: "Malt Beverages", nameAr: "فيروز أناناس 275 مل زجاج",    nameEn: "Fayrouz Pineapple 275ml NRB",   caseCount: 24, pricePerPiece:   9.50, pricePerCarton:  228.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "222", brand: "Fayrouz", category: "Malt Beverages", nameAr: "بيريل 275 مل زجاج",           nameEn: "Birel 275ml NRB",               caseCount: 24, pricePerPiece:   9.50, pricePerCarton:  228.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "223", brand: "Fayrouz", category: "Malt Beverages", nameAr: "فيروز قهوة 250 مل كانز",      nameEn: "Fayrouz Coffee 250ml Can",      caseCount: 12, pricePerPiece:   9.00, pricePerCarton:  108.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "224", brand: "Fayrouz", category: "Malt Beverages", nameAr: "فيروز أناناس 970 مل",         nameEn: "Fayrouz Pineapple 970ml",       caseCount:  6, pricePerPiece:  16.50, pricePerCarton:   99.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "225", brand: "Fayrouz", category: "Malt Beverages", nameAr: "فيروز تفاح 970 مل",           nameEn: "Fayrouz Apple 970ml",           caseCount:  6, pricePerPiece:  16.50, pricePerCarton:   99.00, hasTax: true, image: "/placeholder-product.svg" },

  // ─── EL DOHA — Staples ──────────────────────────────────────────────────────
  { id: "226", brand: "el doha", category: "Rice",  nameAr: "ارز الضحى 1 كجم",   nameEn: "El Doha Rice 1kg",   caseCount: 10, pricePerPiece:  38.80, pricePerCarton:  388.00, hasTax: false, image: "/placeholder-product.svg" },
  { id: "237", brand: "el doha", category: "Sugar", nameAr: "سكر الضحى 1 كجم",   nameEn: "El Doha Sugar 1kg",  caseCount: 10, pricePerPiece:  43.00, pricePerCarton:  430.00, hasTax: false, image: "/placeholder-product.svg" },

  // ─── NESTLE — Coffee ────────────────────────────────────────────────────────
  // Case counts based on standard Egyptian HORECA packaging (jars: 6/carton, 3in1 sachets: 24/carton)
  { id: "227", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه جولد 190 جم",               nameEn: "Nescafé Gold 190g",                   caseCount:  6, pricePerPiece:  450.00, pricePerCarton: 2700.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "228", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه كلاسيك 190 جم",             nameEn: "Nescafé Classic 190g",                caseCount:  6, pricePerPiece:  277.50, pricePerCarton: 1665.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "229", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه كلاسيك باوتش 200 جم",       nameEn: "Nescafé Classic Pouch 200g",          caseCount:  6, pricePerPiece:  552.07, pricePerCarton: 3312.42, hasTax: true, image: "/placeholder-product.svg" },
  { id: "230", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه كلاسيك بلاك ساشيه 1.8 جم", nameEn: "Nescafé Classic Black Sachet 1.8g",   caseCount: 200, pricePerPiece:  23.94, pricePerCarton: 4787.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "231", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه جولد كابتشينو موكا 18 جم",  nameEn: "Nescafé Gold Cappuccino Mocha 18g",   caseCount: 12, pricePerPiece:  154.17, pricePerCarton: 1850.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "232", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه شوت 3×1 شوكولاته وبندق",   nameEn: "Nescafé SHOT 3in1 Choco & Hazelnut",  caseCount: 24, pricePerPiece:   36.86, pricePerCarton:  884.69, hasTax: true, image: "/placeholder-product.svg" },
  { id: "233", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه 3×1 اكسترا شوت",           nameEn: "Nescafé 3in1 Extra Shot",             caseCount: 24, pricePerPiece:   36.74, pricePerCarton:  881.68, hasTax: true, image: "/placeholder-product.svg" },
  { id: "234", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه شوت 3×1 فانيليا وكراميل",  nameEn: "Nescafé SHOT 3in1 Vanilla & Caramel", caseCount: 24, pricePerPiece:   36.44, pricePerCarton:  874.50, hasTax: true, image: "/placeholder-product.svg" },
  { id: "235", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه 3×1 اورجينال 18 جم",       nameEn: "Nescafé 3in1 Original 18g",           caseCount: 24, pricePerPiece:   66.46, pricePerCarton: 1595.00, hasTax: true, image: "/placeholder-product.svg" },
  { id: "236", brand: "Nestle", category: "Coffee", nameAr: "نسكافيه 3×1 بندق 18 جم",           nameEn: "Nescafé 3in1 Hazelnut 18g",           caseCount: 24, pricePerPiece:   66.59, pricePerCarton: 1598.27, hasTax: true, image: "/placeholder-product.svg" },
];

export const categories = [...new Set(products.map((p) => p.category))].sort();
export const brands     = [...new Set(products.map((p) => p.brand))].sort();

export function getProduct(id: string) {
  return products.find((p) => p.id === id);
}
